package com.example.blackjill

object CardDeck {

   val cardList = listOf(
    Cards(R.drawable.ace_of_clubs, 11),
    Cards(R.drawable.ace_of_hearts, 11),
    Cards(R.drawable.ace_of_spades, 11),
    Cards(R.drawable.ace_of_diamonds, 11),
    Cards(R.drawable.two_spades, 2),
    Cards(R.drawable.three_clubs, 3),
    Cards(R.drawable.spades_three, 3),
    Cards(R.drawable.hearts_three, 3),
    Cards(R.drawable.diamonds_three, 3),
    Cards(R.drawable.four_of_hearts, 4),
    Cards(R.drawable.four_of_clubs, 4),
    Cards(R.drawable.four_of_spades, 4),
    Cards(R.drawable.four_of_diamonds, 4),
    Cards(R.drawable.five_of_spades, 5),
    Cards(R.drawable.five_of_clubs, 5),
    Cards(R.drawable.five_of_hearts, 5),
    Cards(R.drawable.five_of_diamonds, 5),
    Cards(R.drawable.six_of_hearts, 6),
    Cards(R.drawable.six_of_clubs, 6),
    Cards(R.drawable.six_of_spades, 6),
    Cards(R.drawable.six_of_diamonds, 6),
    Cards(R.drawable.seven_of_spades, 7),
    Cards(R.drawable.seven_of_clubs, 7),
    Cards(R.drawable.seven_of_hearts, 7),
    Cards(R.drawable.seven_of_diamonds, 7),
    Cards(R.drawable.eight_of_hearts, 8),
    Cards(R.drawable.eight_of_clubs, 8),
    Cards(R.drawable.eight_of_spades, 8),
    Cards(R.drawable.eight_of_diamonds, 8),
    Cards(R.drawable.nine_of_spades, 9),
    Cards(R.drawable.nine_of_clubs, 9),
    Cards(R.drawable.nine_of_hearts, 9),
    Cards(R.drawable.nine_of_diamonds, 9),
    Cards(R.drawable.ten_of_hearts, 10),
    Cards(R.drawable.ten_of_clubs, 10),
    Cards(R.drawable.ten_of_spades, 10),
    Cards(R.drawable.ten_of_diamonds, 10),
    Cards(R.drawable.jack_of_spades, 10),
    Cards(R.drawable.jack_of_clubs, 10),
    Cards(R.drawable.jack_of_hearts, 10),
    Cards(R.drawable.jack_of_diamonds, 10),
    Cards(R.drawable.queen_of_hearts, 10),
    Cards(R.drawable.queen_of_clubs, 10),
    Cards(R.drawable.queen_of_spades, 10),
    Cards(R.drawable.queen_of_diamonds, 10),
    Cards(R.drawable.king_of_spades, 10),
    Cards(R.drawable.king_of_clubs, 10),
    Cards(R.drawable.king_of_hearts, 10),
    Cards(R.drawable.king_of_diamonds, 10)
    )
}